feat(card): (WIP)  Create the component Card Member
grupotesseract/grupotesseract.com.br pull request #34
Opened 2024-03-07 14:17 UTC by Keikonichi

Create the component Card Member that contains team information.

![CardMmberTesseractComponent](https://github.com/grupotesseract/grupotesseract.com.br/assets/93331277/bc1fbbcb-7c4d-4e1d-bd3e-879b503c7418)

2024-03-07 15:11 UTC, thiagobraga requested changes
@Keikonichi I left some comments about this PR. I'll run the branch locally to understand what is happening with images and the structure you created.

2024-03-07 15:11 UTC, thiagobraga commented on app/components/PageTitle.tsx
> +      <div className="box-title flex">
When you have only one direct child inside fragment `<>`, in this case `<div className="box-title flex">`, you don't really need to put the fragment. You would only need the fragment if you had a sibling element, for example:

```jsx
<>
  <div className="element">
    // element contents
  </div>
  <div className="sibling-element">
    // it could be any sibling element, not only div
  </div>
</>
```

So, in your case, you could remove the fragment:

```jsx
return (
  <div className="box-title flex">
    ...
  </div>
);
```

2024-03-07 15:11 UTC, thiagobraga commented on app/components/PreContentText.tsx
> +    <div className="box-pre-text flex ">
Remove space after `flex`.

2024-03-07 15:11 UTC, thiagobraga commented on app/components/PageTitle.tsx
> +import React from 'react';
I think in recent versions of React you don't really need to import React.

2024-03-07 15:11 UTC, thiagobraga commented on app/projetos/page.tsx
> +      })}
### Suggestion

```jsx
export default function Projects() {
  return (
    {boxData.map((item) => (
      <PageTitle
        subtitle1={item.subtitle1}
        subtitleClass={item.subtitleClass}
        title={item.title}
        key={item.key}
      />
    ))}
  );
}
```

2024-03-07 15:11 UTC, thiagobraga commented on app/components/TeamMemberList.tsx
> +  const teamMembers = getTeamMembers();
You can import data file here, just fix the file path if needed:

```jsx
import teamMembers from '../data/team-information.json';
```

Then, after you import data file, you could remove the file `utils/teamMembers.ts`.

2024-03-11 14:47 UTC, thiagobraga approved these changes

2024-03-13 19:19 UTC, Keikonichi commented
This last commit corrects the excess of components that was causing the page to overflow.
And the styles are adjusted for the 1280 screen.

![image](https://github.com/grupotesseract/grupotesseract.com.br/assets/93331277/e7217294-7538-4829-bfc9-a8582794d60e)


@thiagobraga 
@renatoagomes

2024-03-13 19:36 UTC, Keikonichi commented
his is the layout on the screen with a size of 1500

![image](https://github.com/grupotesseract/grupotesseract.com.br/assets/93331277/fc2424ef-088e-425b-97c4-ce0970e0060b)

2024-03-26 23:41 UTC, renatoagomes approved these changes

2024-03-26 23:41 UTC, merged