feat(form): WIP Form component.
grupotesseract/grupotesseract.com.br pull request #42
Opened 2024-03-26 13:23 UTC by Keikonichi

Creates the Form component of the Contact page.

-The style needs to be improved to match the layout
-The data received by the form needs to be sent correctly

![image](https://github.com/grupotesseract/grupotesseract.com.br/assets/93331277/9eb12240-852f-42fd-aa10-78c95d95927c)

2024-04-08 18:24 UTC, Keikonichi commented
I chose to leave the layout at 1024 as shown in the picture because the footer was overflowing.

![image](https://github.com/grupotesseract/grupotesseract.com.br/assets/93331277/8c7f376a-0c63-4a75-b1d5-4968019d93e6)

2024-04-08 18:25 UTC, Keikonichi commented
On the 1280 screen, the layout looks like this

![image](https://github.com/grupotesseract/grupotesseract.com.br/assets/93331277/d7dcc25a-9eec-4ad3-b8c6-1e616fb0dbe1)

2024-04-08 21:17 UTC, Keikonichi commented
The task is finished.
@thiagobraga 
@renatoagomes

2024-04-10 20:49 UTC, renatoagomes requested changes

2024-04-10 20:49 UTC, renatoagomes commented on app/contato/page.tsx
>          </div>
@Keikonichi favor corrigir o errinho de português no 'conversar'

2024-04-15 21:56 UTC, merged